In [633]:
import numpy as np
import pandas as pd

In [634]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [635]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [636]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [637]:
movies.shape

(4803, 20)

In [638]:
credits.shape

(4803, 4)

In [639]:
movies = movies.merge(credits,on ='title')

In [640]:
type(movies)

pandas.core.frame.DataFrame

In [641]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [642]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [643]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [644]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [645]:
movies.dropna(inplace = True)

In [646]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [647]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [648]:
import ast

In [649]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [650]:
 import ast
 ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [651]:
movies['genres'] = movies['genres'].apply(convert)

In [652]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [653]:
movies['keywords'] = movies['keywords'].apply(convert)

In [654]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [655]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [656]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
          L.append(i['name'])
          counter += 1
        else:
           break
    return L

In [657]:
movies['cast'] = movies['cast'].apply(convert3)

In [658]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [659]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
          if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [660]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [661]:
movies['crew'] =  movies['crew'].apply(fetch_director)

In [662]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [663]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())
# string ko list mein

In [664]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [665]:
movies['genres'] = movies['genres'].apply(lambda x :[i.replace(" ","") for i in x ])
movies['keywords'] = movies['keywords'].apply(lambda x :[i.replace(" ","") for i in x ])
movies['cast'] = movies['cast'].apply(lambda x :[i.replace(" ","") for i in x ])
movies['crew'] = movies['crew'].apply(lambda x :[i.replace(" ","") for i in x ])

In [666]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [667]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['cast'] +movies['crew']

In [668]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [669]:
new_df = movies[['movie_id','title','tags']]

In [670]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [671]:
# list ko string mein karenge
new_df['tags']  = new_df['tags'].apply(lambda x:" ".join(x))

/var/folders/vk/07qc5yfn3j130vj5nn3x5cgr0000gn/T/ipykernel_76420/910057515.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']  = new_df['tags'].apply(lambda x:" ".join(x))

In [672]:
!pip install nltk

7302.53s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: nltk in /opt/anaconda3/lib/python3.13/site-packages (3.9.2)
Requirement already satisfied: click in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (4.67.1)

In [673]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [674]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [675]:
new_df['tags'] = new_df['tags'].apply(stem)

/var/folders/vk/07qc5yfn3j130vj5nn3x5cgr0000gn/T/ipykernel_76420/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [676]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [677]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [678]:
 new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

/var/folders/vk/07qc5yfn3j130vj5nn3x5cgr0000gn/T/ipykernel_76420/3946428217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [679]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [680]:
# now we will aonvert text to vector
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [681]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [682]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [683]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [684]:
from sklearn.metrics.pairwise import cosine_similarity

In [685]:
similarity = cosine_similarity(vector)

In [686]:
cosine_similarity(vector).shape

(4806, 4806)

In [687]:
similarity[0]

array([1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
       0.        ], shape=(4806,))

In [688]:

# enumerate used to get both index and value while looping

In [689]:
list(enumerate(similarity[0]))

[(0, np.float64(1.0)),
 (1, np.float64(0.1538967528127731)),
 (2, np.float64(0.08606629658238704)),
 (3, np.float64(0.05923488777590924)),
 (4, np.float64(0.12048289933537483)),
 (5, np.float64(0.15339299776947407)),
 (6, np.float64(0.035355339059327376)),
 (7, np.float64(0.22056438662814232)),
 (8, np.float64(0.08944271909999159)),
 (9, np.float64(0.11180339887498947)),
 (10, np.float64(0.1632993161855452)),
 (11, np.float64(0.11338934190276817)),
 (12, np.float64(0.16269784336399212)),
 (13, np.float64(0.07071067811865475)),
 (14, np.float64(0.17213259316477408)),
 (15, np.float64(0.07669649888473704)),
 (16, np.float64(0.1224744871391589)),
 (17, np.float64(0.13801311186847084)),
 (18, np.float64(0.06030226891555272)),
 (19, np.float64(0.11028219331407116)),
 (20, np.float64(0.07961173386514128)),
 (21, np.float64(0.08451542547285165)),
 (22, np.float64(0.10846522890932808)),
 (23, np.float64(0.15)),
 (24, np.float64(0.08606629658238704)),
 (25, np.float64(0.02795084971874737)),
 (26, np.float64(0.18257418583505539)),
 (27, np.float64(0.16137430609197573)),
 (28, np.float64(0.1732050807568877)),
 (29, np.float64(0.09784921095801634)),
 (30, np.float64(0.11028219331407116)),
 (31, np.float64(0.21693045781865616)),
 (32, np.float64(0.0659380473395787)),
 (33, np.float64(0.158113883008419)),
 (34, np.float64(0.0)),
 (35, np.float64(0.17928429140015906)),
 (36, np.float64(0.1976423537605237)),
 (37, np.float64(0.08770580193070293)),
 (38, np.float64(0.08588975014708022)),
 (39, np.float64(0.12909944487358055)),
 (40, np.float64(0.08451542547285165)),
 (41, np.float64(0.10476454436543672)),
 (42, np.float64(0.0)),
 (43, np.float64(0.15339299776947407)),
 (44, np.float64(0.06741998624632421)),
 (45, np.float64(0.12524485821702988)),
 (46, np.float64(0.18257418583505539)),
 (47, np.float64(0.15655607277128736)),
 (48, np.float64(0.06030226891555272)),
 (49, np.float64(0.0)),
 (50, np.float64(0.12456821978060995)),
 (51, np.float64(0.09045340337332908)),
 (52, np.float64(0.12909944487358055)),
 (53, np.float64(0.0778498944161523)),
 (54, np.float64(0.06201736729460423)),
 (55, np.float64(0.08660254037844385)),
 (56, np.float64(0.158113883008419)),
 (57, np.float64(0.0)),
 (58, np.float64(0.06388765649999399)),
 (59, np.float64(0.08451542547285164)),
 (60, np.float64(0.0)),
 (61, np.float64(0.2051956704170308)),
 (62, np.float64(0.12909944487358058)),
 (63, np.float64(0.0778498944161523)),
 (64, np.float64(0.05590169943749474)),
 (65, np.float64(0.03296902366978935)),
 (66, np.float64(0.03627381250550058)),
 (67, np.float64(0.12048289933537483)),
 (68, np.float64(0.2051956704170308)),
 (69, np.float64(0.04969039949999532)),
 (70, np.float64(0.11180339887498947)),
 (71, np.float64(0.10882143751650175)),
 (72, np.float64(0.18650096164806276)),
 (73, np.float64(0.07071067811865475)),
 (74, np.float64(0.1556997888323046)),
 (75, np.float64(0.09128709291752769)),
 (76, np.float64(0.12048289933537483)),
 (77, np.float64(0.0)),
 (78, np.float64(0.09325048082403138)),
 (79, np.float64(0.11338934190276817)),
 (80, np.float64(0.05163977794943222)),
 (81, np.float64(0.08075728530872482)),
 (82, np.float64(0.09534625892455922)),
 (83, np.float64(0.19364916731037088)),
 (84, np.float64(0.1535737792084878)),
 (85, np.float64(0.07319250547113998)),
 (86, np.float64(0.0778498944161523)),
 (87, np.float64(0.1315587028960544)),
 (88, np.float64(0.1025978352085154)),
 (89, np.float64(0.04170288281141495)),
 (90, np.float64(0.09534625892455922)),
 (91, np.float64(0.16609095970747992)),
 (92, np.float64(0.07905694150420947)),
 (93, np.float64(0.07453559924999298)),
 (94, np.float64(0.21693045781865616)),
 (95, np.float64(0.09534625892455922)),
 (96, np.float64(0.12909944487358055)),
 (97, np.float64(0.10741723110591492)),
 (98, np.float64(0.16269784336399212)),
 (99, np.float64(0.039528470752104736)),
 (100, np.float64(0.05423261445466404)),
 (101, np.float64(0.1315587028960544)),
 (102, np.float64(0.12060453783110545)),
 (103, np.float64(0.10476454436543672)),
 (104, np.float64(0.09759000729485331)),
 (105, np.float64(0.11547005383792514)),
 (106, np.float64(0.07352146220938077)),
 (107, np.float64(0.1318760946791574)),
 (108, np.float64(0.11338934190276817)),
 (109, np.float64(0.12909944487358058)),
 (110, np.float64(0.0)),
 (111, np.float64(0.12909944487358055)),
 (112, np.float64(0.08944271909999159)),
 (113, np.float64(0.07905694150420947)),
 (114, np.float64(0.0778498944161523)),
 (115, np.float64(0.08606629658238704)),
 (116, np.float64(0.08304547985373996)),
 (117, np.float64(0.10540925533894599)),
 (118, np.float64(0.02862991671569341)),
 (119, np.float64(0.042257712736425826)),
 (120, np.float64(0.0)),
 (121, np.float64(0.12456821978060995)),
 (122, np.float64(0.158113883008419)),
 (123, np.float64(0.13987572123604708)),
 (124, np.float64(0.06900655593423542)),
 (125, np.float64(0.06674912392349772)),
 (126, np.float64(0.11858541225631421)),
 (127, np.float64(0.16770509831248423)),
 (128, np.float64(0.0)),
 (129, np.float64(0.10350983390135313)),
 (130, np.float64(0.044721359549995794)),
 (131, np.float64(0.14704292441876154)),
 (132, np.float64(0.07254762501100116)),
 (133, np.float64(0.049999999999999996)),
 (134, np.float64(0.16770509831248423)),
 (135, np.float64(0.0)),
 (136, np.float64(0.03726779962499649)),
 (137, np.float64(0.023186944788008413)),
 (138, np.float64(0.14638501094227996)),
 (139, np.float64(0.15339299776947407)),
 (140, np.float64(0.06984302957695782)),
 (141, np.float64(0.06454972243679029)),
 (142, np.float64(0.09325048082403138)),
 (143, np.float64(0.09784921095801634)),
 (144, np.float64(0.1025978352085154)),
 (145, np.float64(0.03261640365267211)),
 (146, np.float64(0.0)),
 (147, np.float64(0.0816496580927726)),
 (148, np.float64(0.1538967528127731)),
 (149, np.float64(0.17677669529663687)),
 (150, np.float64(0.18257418583505539)),
 (151, np.float64(0.26967994498529685)),
 (152, np.float64(0.09999999999999999)),
 (153, np.float64(0.09128709291752768)),
 (154, np.float64(0.04767312946227961)),
 (155, np.float64(0.0)),
 (156, np.float64(0.03892494720807615)),
 (157, np.float64(0.10540925533894599)),
 (158, np.float64(0.14907119849998596)),
 (159, np.float64(0.11180339887498948)),
 (160, np.float64(0.08519427513705971)),
 (161, np.float64(0.07453559924999298)),
 (162, np.float64(0.049999999999999996)),
 (163, np.float64(0.07905694150420947)),
 (164, np.float64(0.11858541225631421)),
 (165, np.float64(0.1025978352085154)),
 (166, np.float64(0.14638501094227996)),
 (167, np.float64(0.08944271909999159)),
 (168, np.float64(0.15118578920369088)),
 (169, np.float64(0.10882143751650175)),
 (170, np.float64(0.10476454436543672)),
 (171, np.float64(0.039528470752104736)),
 (172, np.float64(0.11952286093343936)),
 (173, np.float64(0.0)),
 (174, np.float64(0.17541160386140586)),
 (175, np.float64(0.08032193289024989)),
 (176, np.float64(0.05773502691896257)),
 (177, np.float64(0.0)),
 (178, np.float64(0.03779644730092272)),
 (179, np.float64(0.05423261445466404)),
 (180, np.float64(0.03726779962499649)),
 (181, np.float64(0.0408248290463863)),
 (182, np.float64(0.11858541225631421)),
 (183, np.float64(0.09682458365518543)),
 (184, np.float64(0.11028219331407116)),
 (185, np.float64(0.08451542547285165)),
 (186, np.float64(0.06454972243679029)),
 (187, np.float64(0.15339299776947407)),
 (188, np.float64(0.035355339059327376)),
 (189, np.float64(0.05976143046671968)),
 (190, np.float64(0.06030226891555272)),
 (191, np.float64(0.0816496580927726)),
 (192, np.float64(0.0)),
 (193, np.float64(0.08808303292720551)),
 (194, np.float64(0.0)),
 (195, np.float64(0.08944271909999159)),
 (196, np.float64(0.09999999999999999)),
 (197, np.float64(0.06984302957695782)),
 (198, np.float64(0.09128709291752769)),
 (199, np.float64(0.20080483222562473)),
 (200, np.float64(0.1414213562373095)),
 (201, np.float64(0.0)),
 (202, np.float64(0.052704627669472995)),
 (203, np.float64(0.1315587028960544)),
 (204, np.float64(0.04016096644512494)),
 (205, np.float64(0.10540925533894599)),
 (206, np.float64(0.16137430609197573)),
 (207, np.float64(0.13693063937629155)),
 (208, np.float64(0.20225995873897262)),
 (209, np.float64(0.052704627669472995)),
 (210, np.float64(0.0778498944161523)),
 (211, np.float64(0.03892494720807615)),
 (212, np.float64(0.11677484162422844)),
 (213, np.float64(0.11180339887498947)),
 (214, np.float64(0.03779644730092272)),
 (215, np.float64(0.12048289933537483)),
 (216, np.float64(0.11180339887498948)),
 (217, np.float64(0.06388765649999399)),
 (218, np.float64(0.05976143046671968)),
 (219, np.float64(0.09128709291752769)),
 (220, np.float64(0.08944271909999159)),
 (221, np.float64(0.03726779962499649)),
 (222, np.float64(0.09045340337332908)),
 (223, np.float64(0.07559289460184544)),
 (224, np.float64(0.061429511683395124)),
 (225, np.float64(0.0778498944161523)),
 (226, np.float64(0.0)),
 (227, np.float64(0.09534625892455922)),
 (228, np.float64(0.1414213562373095)),
 (229, np.float64(0.07851358838853205)),
 (230, np.float64(0.11952286093343936)),
 (231, np.float64(0.0)),
 (232, np.float64(0.19518001458970663)),
 (233, np.float64(0.158113883008419)),
 (234, np.float64(0.10741723110591492)),
 (235, np.float64(0.08770580193070293)),
 (236, np.float64(0.09534625892455922)),
 (237, np.float64(0.09759000729485331)),
 (238, np.float64(0.12171612389003691)),
 (239, np.float64(0.061429511683395124)),
 (240, np.float64(0.08606629658238704)),
 (241, np.float64(0.1224744871391589)),
 (242, np.float64(0.13693063937629155)),
 (243, np.float64(0.11677484162422844)),
 (244, np.float64(0.049999999999999996)),
 (245, np.float64(0.09999999999999999)),
 (246, np.float64(0.03450327796711771)),
 (247, np.float64(0.0)),
 (248, np.float64(0.07071067811865475)),
 (249, np.float64(0.11547005383792514)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.035355339059327376)),
 (253, np.float64(0.06030226891555272)),
 (254, np.float64(0.08304547985373996)),
 (255, np.float64(0.0)),
 (256, np.float64(0.13483997249264842)),
 (257, np.float64(0.08606629658238704)),
 (258, np.float64(0.03131121455425747)),
 (259, np.float64(0.1025978352085154)),
 (260, np.float64(0.1538967528127731)),
 (261, np.float64(0.045643546458763846)),
 (262, np.float64(0.11858541225631421)),
 (263, np.float64(0.15)),
 (264, np.float64(0.0)),
 (265, np.float64(0.045643546458763846)),
 (266, np.float64(0.09999999999999999)),
 (267, np.float64(0.10846522890932808)),
 (268, np.float64(0.042257712736425826)),
 (269, np.float64(0.0)),
 (270, np.float64(0.1267731382092775)),
 (271, np.float64(0.11858541225631421)),
 (272, np.float64(0.0)),
 (273, np.float64(0.03834824944236852)),
 (274, np.float64(0.046373889576016826)),
 (275, np.float64(0.15)),
 (276, np.float64(0.1025978352085154)),
 (277, np.float64(0.09682458365518543)),
 (278, np.float64(0.11504474832710555)),
 (279, np.float64(0.11180339887498947)),
 (280, np.float64(0.0)),
 (281, np.float64(0.07559289460184544)),
 (282, np.float64(0.08770580193070293)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.031008683647302113)),
 (286, np.float64(0.03627381250550058)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0)),
 (289, np.float64(0.07161148740394328)),
 (290, np.float64(0.09534625892455922)),
 (291, np.float64(0.08451542547285165)),
 (292, np.float64(0.1538967528127731)),
 (293, np.float64(0.04767312946227961)),
 (294, np.float64(0.08304547985373996)),
 (295, np.float64(0.042257712736425826)),
 (296, np.float64(0.06900655593423542)),
 (297, np.float64(0.03726779962499649)),
 (298, np.float64(0.0)),
 (299, np.float64(0.06388765649999399)),
 (300, np.float64(0.1267731382092775)),
 (301, np.float64(0.09128709291752768)),
 (302, np.float64(0.08451542547285165)),
 (303, np.float64(0.04152273992686998)),
 (304, np.float64(0.04850712500726659)),
 (305, np.float64(0.11180339887498947)),
 (306, np.float64(0.08770580193070293)),
 (307, np.float64(0.09376144618769908)),
 (308, np.float64(0.05423261445466404)),
 (309, np.float64(0.09999999999999999)),
 (310, np.float64(0.05547001962252292)),
 (311, np.float64(0.16064386578049977)),
 (312, np.float64(0.14509525002200233)),
 (313, np.float64(0.05590169943749474)),
 (314, np.float64(0.0)),
 (315, np.float64(0.1267731382092775)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.09999999999999999)),
 (320, np.float64(0.04767312946227961)),
 (321, np.float64(0.0)),
 (322, np.float64(0.2051956704170308)),
 (323, np.float64(0.0)),
 (324, np.float64(0.03726779962499649)),
 (325, np.float64(0.09128709291752769)),
 (326, np.float64(0.04303314829119352)),
 (327, np.float64(0.045643546458763846)),
 (328, np.float64(0.0)),
 (329, np.float64(0.13693063937629155)),
 (330, np.float64(0.16269784336399212)),
 (331, np.float64(0.06819943394704735)),
 (332, np.float64(0.1267731382092775)),
 (333, np.float64(0.04879500364742666)),
 (334, np.float64(0.11504474832710555)),
 (335, np.float64(0.08606629658238704)),
 (336, np.float64(0.1025978352085154)),
 (337, np.float64(0.03580574370197164)),
 (338, np.float64(0.0)),
 (339, np.float64(0.09128709291752769)),
 (340, np.float64(0.0816496580927726)),
 (341, np.float64(0.09128709291752769)),
 (342, np.float64(0.10927167294163061)),
 (343, np.float64(0.032274861218395144)),
 (344, np.float64(0.042257712736425826)),
 (345, np.float64(0.03162277660168379)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.04767312946227961)),
 (349, np.float64(0.1341640786499874)),
 (350, np.float64(0.07352146220938077)),
 (351, np.float64(0.0)),
 (352, np.float64(0.045643546458763846)),
 (353, np.float64(0.033709993123162106)),
 (354, np.float64(0.0)),
 (355, np.float64(0.06324555320336758)),
 (356, np.float64(0.09534625892455922)),
 (357, np.float64(0.0)),
 (358, np.float64(0.09759000729485331)),
 (359, np.float64(0.04767312946227961)),
 (360, np.float64(0.0)),
 (361, np.float64(0.04303314829119352)),
 (362, np.float64(0.09128709291752769)),
 (363, np.float64(0.06741998624632421)),
 (364, np.float64(0.036760731104690386)),
 (365, np.float64(0.08304547985373996)),
 (366, np.float64(0.08032193289024989)),
 (367, np.float64(0.0)),
 (368, np.float64(0.09534625892455922)),
 (369, np.float64(0.1267731382092775)),
 (370, np.float64(0.09128709291752769)),
 (371, np.float64(0.10476454436543672)),
 (372, np.float64(0.07905694150420947)),
 (373, np.float64(0.11547005383792514)),
 (374, np.float64(0.06324555320336758)),
 (375, np.float64(0.030714755841697562)),
 (376, np.float64(0.07352146220938077)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.07191949522280762)),
 (380, np.float64(0.0)),
 (381, np.float64(0.12403473458920845)),
 (382, np.float64(0.0)),
 (383, np.float64(0.08032193289024989)),
 (384, np.float64(0.045643546458763846)),
 (385, np.float64(0.0)),
 (386, np.float64(0.03779644730092272)),
 (387, np.float64(0.04303314829119352)),
 (388, np.float64(0.0)),
 (389, np.float64(0.09128709291752769)),
 (390, np.float64(0.044721359549995794)),
 (391, np.float64(0.02988071523335984)),
 (392, np.float64(0.043852900965351466)),
 (393, np.float64(0.0)),
 (394, np.float64(0.039528470752104736)),
 (395, np.float64(0.0)),
 (396, np.float64(0.04016096644512494)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.039528470752104736)),
 (400, np.float64(0.15)),
 (401, np.float64(0.0)),
 (402, np.float64(0.07905694150420947)),
 (403, np.float64(0.15971914124998499)),
 (404, np.float64(0.049999999999999996)),
 (405, np.float64(0.04662524041201569)),
 (406, np.float64(0.03162277660168379)),
 (407, np.float64(0.031008683647302113)),
 (408, np.float64(0.05423261445466404)),
 (409, np.float64(0.0)),
 (410, np.float64(0.10606601717798213)),
 (411, np.float64(0.0778498944161523)),
 (412, np.float64(0.13483997249264842)),
 (413, np.float64(0.11504474832710555)),
 (414, np.float64(0.04152273992686998)),
 (415, np.float64(0.05872202195147034)),
 (416, np.float64(0.045643546458763846)),
 (417, np.float64(0.052704627669472995)),
 (418, np.float64(0.0)),
 (419, np.float64(0.10606601717798213)),
 (420, np.float64(0.1813690625275029)),
 (421, np.float64(0.0)),
 (422, np.float64(0.12909944487358058)),
 (423, np.float64(0.04016096644512494)),
 (424, np.float64(0.06324555320336758)),
 (425, np.float64(0.0816496580927726)),
 (426, np.float64(0.08451542547285164)),
 (427, np.float64(0.0408248290463863)),
 (428, np.float64(0.05773502691896257)),
 (429, np.float64(0.0)),
 (430, np.float64(0.04152273992686998)),
 (431, np.float64(0.04662524041201569)),
 (432, np.float64(0.07559289460184544)),
 (433, np.float64(0.04879500364742666)),
 (434, np.float64(0.0)),
 (435, np.float64(0.05423261445466404)),
 (436, np.float64(0.0)),
 (437, np.float64(0.042257712736425826)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0)),
 (440, np.float64(0.0)),
 (441, np.float64(0.04662524041201569)),
 (442, np.float64(0.07905694150420947)),
 (443, np.float64(0.039528470752104736)),
 (444, np.float64(0.0)),
 (445, np.float64(0.0)),
 (446, np.float64(0.043852900965351466)),
 (447, np.float64(0.035355339059327376)),
 (448, np.float64(0.0)),
 (449, np.float64(0.09534625892455922)),
 (450, np.float64(0.03726779962499649)),
 (451, np.float64(0.039528470752104736)),
 (452, np.float64(0.04879500364742666)),
 (453, np.float64(0.04016096644512494)),
 (454, np.float64(0.08304547985373996)),
 (455, np.float64(0.052704627669472995)),
 (456, np.float64(0.06741998624632421)),
 (457, np.float64(0.07352146220938077)),
 (458, np.float64(0.032274861218395144)),
 (459, np.float64(0.05590169943749474)),
 (460, np.float64(0.0)),
 (461, np.float64(0.14301938838683884)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.19999999999999998)),
 (467, np.float64(0.12524485821702988)),
 (468, np.float64(0.045643546458763846)),
 (469, np.float64(0.06523280730534423)),
 (470, np.float64(0.03834824944236852)),
 (471, np.float64(0.07559289460184544)),
 (472, np.float64(0.11504474832710555)),
 (473, np.float64(0.11504474832710555)),
 (474, np.float64(0.0)),
 (475, np.float64(0.10350983390135313)),
 (476, np.float64(0.09999999999999999)),
 (477, np.float64(0.0)),
 (478, np.float64(0.06666666666666667)),
 (479, np.float64(0.026919095102908273)),
 (480, np.float64(0.07559289460184544)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.19518001458970663)),
 (484, np.float64(0.049999999999999996)),
 (485, np.float64(0.08451542547285165)),
 (486, np.float64(0.08195375470622296)),
 (487, np.float64(0.16770509831248423)),
 (488, np.float64(0.0790569415042095)),
 (489, np.float64(0.0)),
 (490, np.float64(0.1732050807568877)),
 (491, np.float64(0.06900655593423542)),
 (492, np.float64(0.04152273992686998)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.22360679774997896)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.1025978352085154)),
 (499, np.float64(0.0)),
 (500, np.float64(0.0408248290463863)),
 (501, np.float64(0.07254762501100116)),
 (502, np.float64(0.07254762501100116)),
 (503, np.float64(0.08451542547285165)),
 (504, np.float64(0.0)),
 (505, np.float64(0.16269784336399212)),
 (506, np.float64(0.0)),
 (507, np.float64(0.17677669529663687)),
 (508, np.float64(0.16064386578049977)),
 (509, np.float64(0.036760731104690386)),
 (510, np.float64(0.08770580193070293)),
 (511, np.float64(0.14638501094227996)),
 (512, np.float64(0.043852900965351466)),
 (513, np.float64(0.11858541225631421)),
 (514, np.float64(0.039528470752104736)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0)),
 (517, np.float64(0.0)),
 (518, np.float64(0.07352146220938077)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.07071067811865475)),
 (524, np.float64(0.0)),
 (525, np.float64(0.0408248290463863)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.039528470752104736)),
 (529, np.float64(0.16854996561581054)),

In [705]:
sorted(list(enumerate(similarity[0])),reverse = True,key = lambda x: x[1])[1:6]
# revere true to get descending order
# lamdada to get apply from 2 index

[(151, np.float64(0.26967994498529685)),
 (4405, np.float64(0.25819888974716115)),
 (942, np.float64(0.24913643956121986)),
 (1440, np.float64(0.2480694691784169)),
 (1192, np.float64(0.2439750182371333))]

In [706]:
new_df[new_df['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [714]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(similarity[movie_index])),reverse=True,key = lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [716]:
recommend('Batman Begins')

Amidst the Devil's Wings
The Dark Knight Rises
The Dark Knight
Batman
Dead Man Down

In [717]:
import pickle

In [720]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [721]:
pickle.dump(similarity,open('similarity.pkl','wb'))